### ISSUE TITLE
Documentation: Mention "Entwicklungslinien" file in README

### ISSUE THREAD

**Issue by corneliusroemer** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#3]
Thanks a lot for publishing all these data to Github, that's amazing! In particular, it's remarkable how quick your turnaround time is, saving a lot of time with respect to GISAID.

One thing that could be improved is mentioning the pango assignment file in the README.

It's very valuable but not very discoverable at the moment. I stumbled upon it only by chance, and others spent a lot of time running sequences through pangolin because they themselves didn't know about that file's existence either.

**Comment by HannesWuensche** [comment]
He @corneliusroemer,

thank you for contributing to our dataset. 

Very true, the documentation for the "Entwicklungslinien" is still missing.  
I forgot it when we extended the dataset with the lineage data. 
We will add it to the documentation as soon as possible, due to the holidays, early January.  

Best regards
@HannesWuensche 
Team RKI | Open Data

**Comment by cuehs** [comment]
fixed by #12
