### ISSUE TITLE
Using nextclade for pango lineage classification

### ISSUE THREAD

**Issue by mg14** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#39]
Hi all. 

The pangolearn release cycles have been slow in the past months for unknown reasons. That's despite a number of fast growing lineages emerging, such as BQ.1, BQ.1.1, XBB or BA.2.3.20.

This is of course problematic as the data released here for Germany doesn't report these variants and suggests, at face value, that none of them were found -- even though BQ.1.1 may already have crossed the 1% mark.

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/6615711/195136266-c43371df-a9d0-4db8-bae0-8f4d7701fbdd.png">

I was therefore wondering whether it would be possible to also provide nextclade lineage assignments as a secondary line of annotation. The underlying reference annotation appears to be updated more regularly.

Thanks,

Moritz

**Comment by mg14** [comment]
I see that today's data has been updated with the release pangolin v.1.15.1 annotation, which contains the variants above. But the issue may still arise in a few weeks time, depending on how quickly pangolin-data is updated.

**Comment by cuehs** [comment]
@mg14 
With the new pango update these lineages should be called correctly. 

Due to lack of resources, we cannot compute nextclade and pangoline in parallel. If this issue comes up again and persists we could change our process to prioritize nextclade as well. 

I would suggest bringing this issue to the attention of the pango-data team. In the end they should be concerned to have an up-to-date process. This delay potentially impacts more sequences than the RKI ones.

**Comment by rgerhards** [comment]
> I would suggest bringing this issue to the attention of the pango-data team. In the end they should be concerned to have an up-to-date process. This delay potentially impacts more sequences than the RKI ones.

sounds like a decent approach - just my 2cts...
