### ISSUE TITLE
(Auto-)Updates of Metadata Files Missing (zenodo.json, govdata.ttl, nfdi4health.json)

### ISSUE THREAD

**Issue by icestorm972** [robert-koch-institut/SARS-CoV-2-Sequenzdaten_aus_Deutschland#55]
Hi,

FYI: the three metadata files are not updated anymore (e.g. for this and last week)

Best regards
David

**Comment by RKIOpenData** [comment]
Hi David,

Part of our publication process is the publication of the data on Zenodo.org. Zenodo made a system update on Friday the 13th and also adapted its API in the process.

This change was not listed in the [documentation](https://help.zenodo.org/docs/about/whats-changed/), so we did not expect to have to make any adjustments to our process beforehand. Unfortunately, our standard processes failed since then because the Zenodo API did not behave as usual. We need the Zenodo service four our metadata files because Zenodo is the endpoint where we get our DOI.

We are currently making adjustments or waiting for a stable service from Zenodo. Until then, we continue to provide the data on Github, but without the metadata and without updates to the DOI in the documentations. The missing Zenodo versions will be added later and the commits adjusted accordingly.

We hope we are soon in a position where we can provide the metadata files again

Best regards
Knut Perseke
for Team RKI | Open Data
